import type { Config } from 'tailwindcss'

export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        // ── Material Design 3 Color System ──
        "primary":                  "#630ed4",
        "primary-container":        "#7c3aed",
        "on-primary":               "#ffffff",
        "on-primary-container":     "#ede0ff",
        "primary-fixed":            "#eaddff",
        "primary-fixed-dim":        "#d2bbff",
        "on-primary-fixed":         "#25005a",
        "on-primary-fixed-variant": "#5a00c6",
        "inverse-primary":          "#d2bbff",
        "secondary":                "#4648d4",
        "secondary-container":      "#6063ee",
        "on-secondary":             "#ffffff",
        "on-secondary-container":   "#fffbff",
        "secondary-fixed":          "#e1e0ff",
        "secondary-fixed-dim":      "#c0c1ff",
        "on-secondary-fixed":       "#07006c",
        "on-secondary-fixed-variant": "#2f2ebe",
        "tertiary":                 "#704500",
        "tertiary-container":       "#905b00",
        "on-tertiary":              "#ffffff",
        "on-tertiary-container":    "#ffe1c0",
        "tertiary-fixed":           "#ffddb8",
        "tertiary-fixed-dim":       "#ffb95f",
        "on-tertiary-fixed":        "#2a1700",
        "on-tertiary-fixed-variant":"#653e00",
        "surface":                  "#fcf8ff",
        "surface-dim":              "#dbd6fb",
        "surface-bright":           "#fcf8ff",
        "surface-container-lowest": "#ffffff",
        "surface-container-low":    "#f6f1ff",
        "surface-container":        "#f0ebff",
        "surface-container-high":   "#eae5ff",
        "surface-container-highest":"#e3dfff",
        "on-surface":               "#1a1833",
        "on-surface-variant":       "#4a4455",
        "surface-variant":          "#e3dfff",
        "inverse-surface":          "#2f2d49",
        "inverse-on-surface":       "#f3eeff",
        "surface-tint":             "#732ee4",
        "outline":                  "#7b7487",
        "outline-variant":          "#ccc3d8",
        "background":               "#fcf8ff",
        "on-background":            "#1a1833",
        "error":                    "#ba1a1a",
        "error-container":          "#ffdad6",
        "on-error":                 "#ffffff",
        "on-error-container":       "#93000a",

        // ── Legacy bridge tokens (kept for backward compat during migration) ──
        app: {
          bg: 'var(--app-bg)',
          surface: 'var(--surface)',
        },
        border: {
          DEFAULT: 'var(--border-color)',
          hover: 'var(--border-hover)',
        },
        text: {
          primary: 'var(--text-primary)',
          muted: 'var(--text-muted)',
          hint: 'var(--text-hint)',
        },
        step1: {
          DEFAULT: 'var(--step1-accent)',
          text: 'var(--step1-text)',
          bg: 'var(--step1-bg)',
          border: 'var(--step1-border)',
        },
        step2: {
          DEFAULT: 'var(--step2-accent)',
          text: 'var(--step2-text)',
          bg: 'var(--step2-bg)',
          border: 'var(--step2-border)',
        },
        step3: {
          DEFAULT: 'var(--step3-accent)',
          text: 'var(--step3-text)',
          bg: 'var(--step3-bg)',
          border: 'var(--step3-border)',
        },
        ai: {
          DEFAULT: 'var(--ai-text)',
          bg: 'var(--ai-bg)',
          border: 'var(--ai-border)',
        },
        danger: {
          DEFAULT: 'var(--danger)',
          bg: 'var(--danger-bg)',
        },
        accent: {
          DEFAULT: 'var(--accent)',
          dark: 'var(--accent-dark)',
          light: 'var(--accent-light)',
          border: 'var(--accent-border)',
        },
        sidebar: {
          bg: 'var(--sidebar-bg)',
          active: 'var(--sidebar-active)',
          'active-border': 'var(--sidebar-active-border)',
        },
      },
      fontFamily: {
        headline: ['Manrope', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
        sans: ['Inter', '-apple-system', 'BlinkMacSystemFont', 'Segoe UI', 'sans-serif'],
        mono: ['SF Mono', 'Monaco', 'Consolas', 'monospace'],
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        '2xl': '1rem',
        '3xl': '1.5rem',
        full: '9999px',
        // Legacy bridge
        card: '14px',
        btn: '9px',
        pill: '20px',
      },
    },
  },
  plugins: [],
} satisfies Config
